### ISSUE TITLE
No `pest_ascii_tree`?

### ISSUE THREAD

**Issue by ctrlcctrlv** [pest-parser/awesome-pest#5]
Really useful tool. Only ever saw one release, five years ago, yet still works on Pest 2.7, which I think is a sign that @Robert42 did a quality job. But maybe it's not included due to this?

I use it all the time when writing Pest grammars.

![Screenshot_20240925_142908](https://github.com/user-attachments/assets/82b78a86-8f9f-4776-86f2-89661752ea69)

https://github.com/Robert42/pest_ascii_tree

**Comment by tomtau** [comment]
@ctrlcctrlv it looks awesome, feel free to open a PR to add it to the list
